name: pack
on:
  workflow_dispatch:
    inputs:
      pack-theme-items:
        description: 'pack theme items'
        required: false
  # schedule:
  #   - cron: '0 23 * * *'

jobs:
  release-worker:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      ___X_CMD_GHACTION_X: x2
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITCODE_TOKEN: ${{ secrets.GITCODE_TOKEN_SYNC }}
      ssh_key: ${{ secrets.SSH_QIAKAI_KEY }}
      git_user: l
      git_email: l@x-cmd.com
      CONCURRENCY: 10
      INPUTS_PACK_THEME_ITEMS: ${{ github.event.inputs.pack-theme-items }}
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: |
            x ws cd-source-code || return
            x ws pack
